export const darkTheme = {
  colors: {
    primary: '#FFAD1D',
    primary1: '#FFC668',
    primary2: '#FFDEA4',
    primary3: '#FEF8E0',
    secondary: '#DA6317',
    secondary1: '#E38751',
    secondary2: '#E6A986',
    secondary3: '#E3CBBC',
    secondaryBtn: '#F9FAFE',
    tertiary: '#25C97C',
    tertiary1: '#2ECF80',
    tertiary2: '#23C77C',
    tertiary3: '#F0F9F5',
    background: '#1D203A',
    background5: '#1D203A',
    background10: '#1D203A',
    white: '#fff',
    white60: '#FFFFF99',
    black: '#09051C',
    grey: '#444352',
    lightGrey: '#86848F',
    lightGrey1: '#CECDD2',
    lightGrey2: '#F4F4F4',
    red: '#FF1D1D',
    red1: '#FFE8E8',
    error: '#edfe00',
    transparent: 'transparent',
    textPrimary: '#FFAD1D',
  },
  fonts: {
    size: {
      xs: 10,
      s: 14,
      m: 16,
      l: 18,
      xl: 20,
      xxl: 26,
      xxxl: 30,
    },
    family: {
      lato: 'Lato-Regular',
      latoLight: 'Lato-Light',
      latoBold: 'Lato-Bold',
      nexaBold: 'Nexa-Bold',
      nexaLight: 'Nexa-Light',
      benton: 'BentonSans-Regular',
      bentonLight: 'BentonSans-Light',
      bentonBold: 'BentonSans-Bold',
      bentonMedium: 'BentonSans-Medium',
      bentonBook: 'BentonSans-Book',
    },
  },
  border: {
    radius5: 5,
    radius10: 10,
    radius15: 10,
    radius25: 25,
    radius30: 30,
    radius50: 50,
  },
};
