export const uiConstants = {
	SET_THEME: 'ui/SET_THEME',
	SET_STATUS: 'ui/SET_STATUS',
	SET_ON_SYNC: 'ui/SET_ON_SYNC',
	CLEAR_ERRORS: 'ui/CLEAR_ERRORS',
	PASS_RESET_SUCCESS: 'ui/PASS_RESET_SUCCESS',
	CLEAR_PASS_RESET_STATUS: 'ui/CLEAR_PASS_RESET_STATUS',
};
