export const userConstants = {
  LOGIN: 'user/LOGIN',
  LOG_OUT: 'user/LOG_OUT',
  SIGN_UP: 'user/SIGN_UP',
  PASSWORD_RESET: 'user/PASSWORD_RESET',

  SET_USER_INFO: 'user/SET_USER_INFO',

  GET_USER_ADS: 'user/GET_USER_ADS',
  UPDATE_USER_INFO: 'user/UPDATE_USER_INFO',
  CLEAR_USER_STATE: 'user/CLEAR_USER_STATE',
  ADD_ADDRESS: 'user/ADD_ADDRESS',
  REMOVE_ADDRESS: 'user/REMOVE_ADDRESS',
  EDIT_ADDRESS: 'user/EDIT_ADDRESS',
  CREATE_NEW_AD: 'user/CREATE_NEW_AD',
};
