export const cartConstants = {
  CLEAR_CART: 'cart/CLEAR_CART',
  UPDATE_CART: 'cart/UPDATE_CART',
  CHECK_CART_ACTIONS: 'cart/CHECK_CART_ACTIONS',
  GET_CART_TOTALS: 'cart/GET_CART_TOTALS',
  SET_SHIPPING_ADDRESS: 'cart/SET_SHIPPING_ADDRESS',
  SET_CART_STAGE: 'cart/SET_CART_STAGE',
  NAVIGATE_CART: 'cart/NAVIGATE_CART',
  ADD_TO_CART: 'cart/ADD_TO_CART',
  UPDATE_CART_TOTALS: 'cart/UPDATE_TOTALS',
  CART_FINISH_PURCHASE: 'cart/CART_FINISH_PURCHASE',
  REMOVE_FROM_CART: 'cart/REMOVE_FROM_CART',
};
