export const cartConstants = {
  CLEAR_CART: 'cart/CLEAR_CART',
  UPDATE_CART: 'cart/UPDATE_CART',
  CHECK_CART_ACTIONS: 'cart/CHECK_CART_ACTIONS',
  GET_CART_TOTALS: 'cart/GET_CART_TOTALS',

  ADD_TO_CART: 'cart/ADD_TO_CART',
  UPDATE_CART_TOTALS: 'cart/UPDATE_TOTALS',
  REMOVE_FROM_CART: 'cart/REMOVE_FROM_CART',
};
