export const appConstants = {
  PICK_IMAGE: 'app/PICK_IMAGE',
  SET_ALL_ADS: 'app/SET_ALL_ADS',
  SET_LANGUAGE: 'app/SET_LANGUAGE',
  FETCH_ALL_ADS: 'app/FETCH_ALL_ADS',
  SET_CATEGORIES: 'app/SET_CATEGORIES',
  SET_TEMP_IMAGES: 'app/SET_TEMP_IMAGES',
  UPLOAD_AD_IMAGES: 'app/UPLOAD_AD_IMAGES',
  FETCH_CATEGORIES: 'app/FETCH_CATEGORIES',
  SET_COMPANY_INFO: 'app/SET_COMPANY_INFO',
  SET_ALL_COMPANIES: 'app/SET_ALL_COMPANIES',
  FETCH_COMPANY_INFO: 'app/FETCH_COMPANY_INFO',
  FETCH_ALL_COMPANIES: 'app/FETCH_ALL_COMPANIES',
};
