export const appConstants = {
  PICK_IMAGE: 'app/PICK_IMAGE',
  SET_ALL_ADS: 'app/SET_ALL_ADS',
  SET_LANGUAGE: 'app/SET_LANGUAGE',
  FETCH_ALL_ADS: 'app/FETCH_ALL_ADS',
  SET_COMPANY_INFO: 'app/SET_COMPANY_INFO',
  GET_COMPANY_INFO: 'app/GET_COMPANY_INFO',
  SET_TEMP_CATEGORIES: 'app/SET_TEMP_CATEGORIES',
  SET_TEMP_IMAGES: 'app/SET_TEMP_IMAGES',
  UPLOAD_AD_IMAGES: 'app/UPLOAD_AD_IMAGES',
};
