import * as faker from 'faker';

const data = {
  produce: [
    {
      id: '3',
      title: 'Bakery',
      image:
        'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80',
    },
    {
      id: '1',
      title: 'Vegetables',
      image:
        'https://images.unsplash.com/photo-1598030304671-5aa1d6f21128?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1934&q=80',
    },
    {
      id: '0',
      title: 'Meat',
      image:
        'https://images.unsplash.com/photo-1448907503123-67254d59ca4f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1049&q=80',
    },
    {
      id: '4',
      title: 'Dairy',
      image:
        'https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&dpr=2&h800&w=600',
    },
    {
      id: '5',
      title: 'Drinks',
      image: 'https://i.imgur.com/vgJY0z3.jpg',
    },
    {
      id: '6',
      title: 'Fish',
      image: 'https://i.imgur.com/vgJY0z3.jpg',
    },
  ],
  companies: [
    {
      id: faker.datatype.uuid(),
      title: faker.company.companyName(),
      image: 'https://picsum.photos/200/300',
      description: 'We make the best cupcakes in the world!',
      website: 'http://cakefactory.com',
      categories: ['0', '1', '2'],
      address: {
        street: faker.address.streetName(),
        city: faker.address.city(),
        postCode: faker.address.zipCode(),
      },
      produce: [
        {
          id: faker.datatype.uuid(),
          owner: faker.company.companyName(),
          title: faker.commerce.productName(),
          category: 1,
          image: faker.random.image('unsplash'),
          description: faker.commerce.productDescription(),
          price: faker.commerce.price(),
          rating: faker.datatype.number({ min: 1, max: 5 }),
          delivery: true,
          available: true,
        },
        {
          id: faker.datatype.uuid(),
          owner: faker.company.companyName(),
          title: faker.commerce.productName(),
          category: 2,
          image: faker.random.image('unsplash'),
          description: faker.commerce.productDescription(),
          price: faker.commerce.price(),
          rating: faker.datatype.number({ min: 1, max: 5 }),
          delivery: true,
          available: true,
        },
        {
          id: faker.datatype.uuid(),
          owner: faker.company.companyName(),
          title: faker.commerce.productName(),
          category: 0,
          image: faker.random.image('unsplash'),
          description: faker.commerce.productDescription(),
          price: faker.commerce.price(),
          rating: faker.datatype.number({ min: 1, max: 5 }),
          delivery: true,
          available: true,
        },
      ],
      rating: faker.datatype.number({ min: 1, max: 5 }),
      phone: faker.phone.phoneNumber(),
      email: faker.internet.email(),
    },
  ],
  products: [
    {
      id: faker.datatype.uuid(),
      owner: faker.company.companyName(),
      title: faker.commerce.productName(),
      category: 'baked',
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      rating: faker.datatype.number({ min: 1, max: 5 }),
      delivery: true,
      available: true,
    },
    {
      id: faker.datatype.uuid(),
      owner: faker.company.companyName(),
      title: faker.commerce.productName(),
      category: 'baked',
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      rating: faker.datatype.number({ min: 1, max: 5 }),
      delivery: false,
      available: true,
    },
    {
      id: faker.datatype.uuid(),
      owner: faker.company.companyName(),
      title: faker.commerce.productName(),
      category: 'dairy',
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      rating: faker.datatype.number({ min: 1, max: 5 }),
      delivery: true,
      available: true,
    },
    {
      id: faker.datatype.uuid(),
      owner: faker.company.companyName(),
      title: faker.commerce.productName(),
      category: 'meat',
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      rating: faker.datatype.number({ min: 1, max: 5 }),
      delivery: false,
      available: true,
    },
    {
      id: faker.datatype.uuid(),
      owner: faker.company.companyName(),
      title: faker.commerce.productName(),
      category: 'vegFruit',
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      rating: faker.datatype.number({ min: 1, max: 5 }),
      delivery: false,
      available: false,
    },
    {
      id: faker.datatype.uuid(),
      owner: faker.company.companyName(),
      title: faker.commerce.productName(),
      category: 'meat',
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      rating: faker.datatype.number({ min: 1, max: 5 }),
      delivery: true,
      available: true,
    },
    {
      id: faker.datatype.uuid(),
      owner: faker.company.companyName(),
      title: faker.commerce.productName(),
      category: 'vegFruit',
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      rating: faker.datatype.number({ min: 1, max: 5 }),
      delivery: true,
      available: true,
    },
    {
      id: faker.datatype.uuid(),
      owner: faker.company.companyName(),
      title: faker.commerce.productName(),
      category: 'dairy',
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      rating: faker.datatype.number({ min: 1, max: 5 }),
      delivery: true,
      available: true,
    },
    {
      id: faker.datatype.uuid(),
      owner: faker.company.companyName(),
      title: faker.commerce.productName(),
      category: 'drinks',
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      rating: faker.datatype.number({ min: 1, max: 5 }),
      delivery: true,
      available: true,
    },
  ],
  ads: [
    {
      id: faker.datatype.uuid(),
      title: faker.commerce.product(),
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      date: faker.date.past(),
      author: {
        id: faker.datatype.uuid(),
        name: faker.name.findName(),
        email: faker.internet.email(),
        city: faker.address.city(),
      },
    },
    {
      id: faker.datatype.uuid(),
      title: faker.commerce.product(),
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      date: faker.date.past(),
      author: {
        id: faker.datatype.uuid(),
        name: faker.name.findName(),
        email: faker.internet.email(),
        city: faker.address.city(),
      },
    },
    {
      id: faker.datatype.uuid(),
      title: faker.commerce.product(),
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      date: faker.date.past(),
      author: {
        id: faker.datatype.uuid(),
        name: faker.name.findName(),
        email: faker.internet.email(),
        city: faker.address.city(),
      },
    },
    {
      id: faker.datatype.uuid(),
      title: faker.commerce.product(),
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      date: faker.date.past(),
      author: {
        id: faker.datatype.uuid(),
        name: faker.name.findName(),
        email: faker.internet.email(),
        city: faker.address.city(),
      },
    },
    {
      id: faker.datatype.uuid(),
      title: faker.commerce.product(),
      image: faker.random.image('unsplash'),
      description: faker.commerce.productDescription(),
      price: faker.commerce.price(),
      date: faker.date.past(),
      author: {
        id: faker.datatype.uuid(),
        name: faker.name.findName(),
        email: faker.internet.email(),
        city: faker.address.city(),
      },
    },
  ],
};
export default data;
